import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tableBackground: {
    position: 'absolute',
    width: '100%',
    height: '100%',

  },
  gameTitle: {
    position: 'absolute',
    top: 8,
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFF',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  botsContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    gap: 6,
  },
  botContainer: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#555',
  },
  botName: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
  },
  botBalance: {
    color: '#ddd',
    fontSize: 12,
  },
  botBet: {
    marginTop: 4,
    fontWeight: 'bold',
    fontSize: 12,
  },
  middleCardArea: {
    position: 'absolute',
    top: '38%',
    alignItems: 'center',
    zIndex: 100,
  },
  middleCardLabel: {
    color: '#FFF',
    fontSize: 13,
    marginBottom: 6,
    fontWeight: 'bold',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  gameArea: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    height: '28%',
    marginTop: '18%',
  },
  sideBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  andarBox: {
    marginRight: 4,
  },
  baharBox: {
    marginLeft: 4,
  },
  sideTitle: {
    position: 'absolute',
    top: 6,
    fontSize: 16,
    fontWeight: 'bold',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  andarTitle: {
    color: '#4CAF50',
  },
  baharTitle: {
    color: '#F44336',
  },
  dividerLine: {
    width: 1.5,
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  cardContainer: {
    position: 'relative',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  card: {
    width: 50,
    height: 75,
    backgroundColor: '#FFF',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.6,
    shadowRadius: 1.5,
    elevation: 4,
  },
  middleCard: {
    position: 'relative',
    top: 0,
    left: 0,
    transform: [{ scale: 1.1 }],
  },
  matchedCard: {
    transform: [{ scale: 1.1 }],
  },
  matchedCardText: {
    fontSize: 20,
  },
  cardText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  redCard: {
    color: '#F44336',
  },
  blackCard: {
    color: '#000',
  },
  matchIndicator: {
    position: 'absolute',
    bottom: -18,
    backgroundColor: 'rgba(255, 235, 59, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  matchIndicatorText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 11,
  },
  gameInfo: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 8,
    borderRadius: 6,
  },
  balanceText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  betText: {
    color: '#FFF',
    fontSize: 14,
    marginTop: 4,
  },
  controlsContainer: {
    position: 'absolute',
    bottom: 20,
    width: '90%',
    alignItems: 'center',
  },
  betControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 14,
  },
  betButton: {
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.7,
    shadowRadius: 2,
    elevation: 4,
  },
  andarButton: {
    backgroundColor: '#4CAF50',
  },
  baharButton: {
    backgroundColor: '#F44336',
  },
  betButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  betAmountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  betAmountLabel: {
    color: '#FFF',
    fontSize: 14,
    marginRight: 8,
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  betAmountControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  betAdjustButton: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 4,
    marginHorizontal: 4,
  },
  betAdjustButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  currentBetAmount: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginHorizontal: 8,
    minWidth: 40,
    textAlign: 'center',
    textShadowColor: '#000',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  gameStatusContainer: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 10,
    borderRadius: 8,
  },
  gameStatusText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  resultOverlay: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -90 }, { translateY: -40 }],
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
  },
  resultText: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  skipButton: {
    backgroundColor: '#FF5722',
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignSelf: 'center',
    width: 100,
  },
  skipButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  playerItem: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 8,
    marginRight: 5,
    borderRadius: 5,
    minWidth: 120,
  },
  currentPlayer: {
    borderWidth: 1,
    borderColor: 'gold',
  },
  playerName: {
    color: 'white',
    fontWeight: 'bold',
  },
  playerBalance: {
    color: 'gold',
  },
  playerBetInfo: {
    color: 'white',
    fontSize: 12,
  },
  connectionStatus: {
    position: 'absolute',
    top: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 5,
    borderRadius: 5,
  },
  connectionDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 5,
  },
  connected: {
    backgroundColor: 'green',
  },
  disconnected: {
    backgroundColor: 'red',
  },
  connectionText: {
    color: 'white',
    fontSize: 12,
  },
  playersContainer: {
    position: 'absolute',
    top: 20,
    left: 20,
    flexDirection: 'row',
    flexWrap: 'wrap',
    maxWidth: '80%',
  },
  timerText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  playerCard: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 8,
    padding: 8,
    margin: 4,
    alignItems: 'center',
    minWidth: 80,
  },
  currentPlayerCard: {
    borderWidth: 2,
    borderColor: 'gold',
  },
  playerNameCard: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
  },
  playerBalanceCard: {
    color: 'lightgreen',
    fontSize: 12,
  },
  playerBet: {
    marginTop: 4,
    padding: 4,
    borderRadius: 4,
    minWidth: 40,
  },
  andarBet: {
    backgroundColor: 'rgba(255,0,0,0.3)',
    borderColor: 'red',
  },
  baharBet: {
    backgroundColor: 'rgba(0,0,255,0.3)',
    borderColor: 'blue',
  },
  playerBetText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  leaveRoomButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: '#F44336',
    padding: 10,
    borderRadius: 5,
  },
  leaveRoomButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  roomSelectionContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  roomSelectionTitle: {
    color: 'white',
    fontSize: 24,
    marginBottom: 20,
    fontWeight: 'bold',
  },
  roomInput: {
    backgroundColor: 'white',
    width: '80%',
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    fontSize: 16,
  },
  roomIdContainer: {
    flexDirection: 'row',
    width: '80%',
    alignItems: 'center',
  },
  randomRoomButton: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 10,
    marginLeft: 10,
  },
  randomRoomButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  roomButtonContainer: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-between',
  },
  roomButton: {
    padding: 15,
    borderRadius: 10,
    width: '48%',
    alignItems: 'center',
  },
  joinRoomButton: {
    backgroundColor: '#2196F3',
  },
  createRoomButton: {
    backgroundColor: '#FF9800',
  },
  roomButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  jokerRevealContainer: {
    position: 'absolute',
    top: '30%',
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 20,
    borderRadius: 10,
    alignItems: 'center',
    zIndex: 100,
  },
  jokerRevealText: {
    color: 'gold',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    textShadowColor: 'black',
    textShadowRadius: 5,
  },
  jokerRevealTimer: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  betTimerContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 10,
    borderRadius: 5,
    zIndex: 100,
  },
  betTimerText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },

  cardValue: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  cardSuit: {
    fontSize: 28,
    marginTop: -5,
  },

});