import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0A0A1F',
    zIndex: 1000,
  },
  container: {
    flex: 1,
    backgroundColor: '#0A0A1F',
  },
header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 40,
    paddingBottom: 10,
    backgroundColor: "#1e293b",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFD700',
  },
    menuButton: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
  },
  profileContainer: {
    padding: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#FFD700',
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#00FF00',
    borderWidth: 2,
    borderColor: '#0A0A1F',
  },
  userInfo: {
    alignItems: 'flex-start',
  },
  username: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  balanceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 15,
  },
  balance: {
    color: '#FFD700',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 5,
  },
  closeButton: {
    padding: 5,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  section: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFF',
    marginBottom: 15,
    textAlign: 'left',
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#363663',
    borderRadius: 12,
    padding: 15,
    backgroundColor: 'rgba(30, 30, 63, 0.5)',
    marginBottom: 15,
  },
  currencySymbol: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFD700',
    marginRight: 8,
  },
  amountInput: {
    flex: 1,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFF',
    padding: 0,
  },
  quickAmounts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickAmountButton: {
    backgroundColor: 'rgba(30, 30, 63, 0.7)',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#363663',
  },
  quickAmountButtonSelected: {
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    borderColor: '#FFD700',
  },
  quickAmountText: {
    color: '#CBD5E1',
    fontWeight: '500',
  },
  quickAmountTextSelected: {
    color: '#FFD700',
    fontWeight: 'bold',
  },
  methodButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderWidth: 1,
    borderColor: '#363663',
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: 'rgba(30, 30, 63, 0.5)',
  },
  methodButtonSelected: {
    borderColor: '#FFD700',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
  },
  methodIconContainer: {
    width: 40,
    alignItems: 'center',
  },
  methodText: {
    flex: 1,
    fontSize: 16,
    color: '#CBD5E1',
    marginLeft: 10,
  },
  methodTextSelected: {
    color: '#FFD700',
    fontWeight: '600',
  },
  selectedIndicator: {
    padding: 4,
  },
  promoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(74, 20, 140, 0.3)',
    padding: 20,
    paddingTop : 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#9C27B0',
  },
    inputGroupWithSpacer: {
    marginBottom: 40,
  },
  promoIconContainer: {
    marginRight: 15,
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
    padding: 10,
    borderRadius: 12,
  },
  promoTextContainer: {
    flex: 1,
  },
  promoTitle: {
    color: '#FFD700',
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 4,
  },
  promoSubtitle: {
    color: '#FFF',
    fontSize: 14,
  },
  footer: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#1A1A3A',
    backgroundColor: '#1A1A3A',
  },
  depositButton: {
    backgroundColor: '#FFD700',
    padding: 18,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  depositButtonDisabled: {
    backgroundColor: '#2D2D2D',
  },
  depositButtonText: {
    color: '#0A0A1F',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default styles;