import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a5c36',
  },
  tableImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    marginTop: 2,
    resizeMode: 'cover',
  },
  playerContainer: {
    alignItems: 'center',
  },
  playerInfo: {
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 8,
    borderRadius: 20,
    marginBottom: 10,
    minWidth: 100,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  activePlayerAvatar: {
    borderWidth: 2,
    borderColor: 'gold',
  },
  playerName: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
  },
  handStrength: {
    color: 'gold',
    fontSize: 10,
  },
  chips: {
    color: 'white',
    fontSize: 10,
  },
  betAmount: {
    color: 'gold',
    fontSize: 10,
  },
  cardsRow: {
    flexDirection: 'row',
    marginTop: 5,
  },
  card: {
    width: 28,
    height: 42,
    backgroundColor: 'white',
    borderRadius: 4,
    marginHorizontal: 1,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 5,
  },
  hiddenCard: {
    backgroundColor: '#1a3a8f',
  },
  currentPlayerCard: {
    borderWidth: 2,
    borderColor: 'gold',
  },
  cardText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  controls: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  button: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 10,
    borderRadius: 20,
    margin: 5,
    minWidth: 80,
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  showButton: {
    backgroundColor: 'rgba(218,165,32,0.8)',
    marginLeft: 150,
  },
  pauseButton: {
    backgroundColor: 'rgba(255,0,0,0.7)',
  },
  playButton: {
    backgroundColor: 'rgba(0,128,0,0.7)',
  },
  timerText: {
    color: 'white',
    alignSelf: 'center',
    margin: 10,
    fontWeight: 'bold',
  },
  winnerOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    zIndex: 100,
  },
  winnerText: {
    color: 'gold',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  potWonText: {
    color: 'white',
    fontSize: 18,
    marginTop: 20,
  },
  potContainer: {
    position: 'absolute',
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 10,
    borderRadius: 20,
    zIndex: 10,
    alignItems: 'center',
  },
  potText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
  chipAmountText: {
    backgroundColor: 'rgba(0,0,0,0.7)',
    color: 'white',
    padding: 2,
    borderRadius: 4,
    marginLeft: 5,
    fontSize: 12,
    fontWeight: 'bold',
  },
  menuButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 999,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  menuButtonText: {
    fontSize: 24,
    color: 'white',
    textAlign: 'center',
    lineHeight: 40,
  },
  menuOverlay: {
  flex: 1,
  backgroundColor: 'rgba(30, 30, 63, 0.7)',
  justifyContent: 'center',
  alignItems: 'center',
},
  menuItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  closeMenuItem: {
    borderBottomWidth: 0,
    backgroundColor: 'rgba(255,50,50,0.3)',
    borderRadius: 5,
    marginTop: 5,
    marginHorizontal: 10,
    marginBottom: 5,
  },
  chatButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatButtonText: {
    fontSize: 24,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    paddingBottom: 20,
    paddingLeft: 90,
    
  },
  modalContent: {
    width: '80%',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
  },
  modalTitle: {
    fontSize: 20,
    marginBottom: 15,
  },
 closeButton: {
  position: 'absolute',
  top: 15,
  right: 15,
  zIndex: 10,
},
  topBar: {
    position: 'absolute',
    top: 10,
    left: 10,
    right: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 10,
  },
  chatBubble: {
    position: 'absolute',
    bottom: 100,
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    maxWidth: 120,
    alignSelf: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  chatText: {
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
  },
  chatInputContainer: {
    position: 'absolute',
    bottom: 10,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chatInput: {
    color: '#fff',
    fontSize: 14,
    height: 40,
  },
  chatIconButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  sendButton: {
    padding: 10,
  },
  cardShowButton: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 10,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  cardShowButtonText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  settingsButton: {
    position: 'absolute',
    right: 20,
    top: 10,
    padding: 10,
    zIndex: 100,
  },
  disabledButton: {
    opacity: 0.5,
  },
  gameStartingText: {
    color: 'white',
    fontSize: 16,
    marginTop: 10,
    textAlign: 'center',
  },
  profileStatusContainer: {
    position: 'absolute',
    right: 20,
    top: 40,
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    zIndex: 100,
  },
  profileStatusText: {
    color: 'white',
    fontSize: 12,
  },
  profileChips: {
    color: 'gold',
    fontWeight: 'bold',
    fontSize: 14,
  },
    timerWarning: {
    borderWidth: 2,
    borderColor: 'red',
  },
  playerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  roomSetupContainer: {
    position: 'absolute',
    top: '20%',
    left: '10%',
    right: '10%',
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 20,
    borderRadius: 20,
    alignItems: 'center',
  },
  setupTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    width: '100%',
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
    color: '#333',
  },
  buttonGroup: {
    width: '100%',
    alignItems: 'center',
  },
  roomButton: {
    backgroundColor: 'rgba(218,165,32,0.8)',
    padding: 12,
    borderRadius: 20,
    width: '100%',
    alignItems: 'center',
    marginVertical: 5,
  },
  orText: {
    color: 'white',
    marginVertical: 10,
    fontWeight: 'bold',
  },
  waitingRoom: {
    position: 'absolute',
    top: '20%',
    left: '10%',
    right: '10%',
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 20,
    borderRadius: 20,
    alignItems: 'center',
  },
  waitingTitle: {
    color: 'gold',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  waitingText: {
    color: 'white',
    fontSize: 16,
    marginBottom: 10,
  },
  startButton: {
    backgroundColor: 'rgba(0,200,0,0.8)',
    padding: 15,
    borderRadius: 20,
    marginTop: 20,
  },
  startButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  // countdownContainer: {
  //   position: 'absolute',
  //   top: 0,
  //   bottom: 0,
  //   left: 0,
  //   right: 0,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: 'rgba(0,0,0,0.7)',
  //   zIndex: 100,
  // },
  // countdownText: {
  //   color: 'gold',
  //   fontSize: 72,
  //   fontWeight: 'bold',
  // },
  chipImage: {
    width: 30,
    height: 30,
  },
  roundText: {
    color: 'white',
    fontSize: 14,
    marginTop: 5,
  },
  actionBar: {
  position: 'absolute',
  bottom: 20,
  left: 0,
  right: 0,
  flexDirection: 'row',
  justifyContent: 'space-around',
  paddingHorizontal: 20,
  zIndex: 1000,
},
betButton: {
  backgroundColor: 'rgba(218,165,32,0.8)',
  padding: 15,
  borderRadius: 20,
  minWidth: 100,
  alignItems: 'center',
},
betButtonText: {
  color: 'white',
  fontWeight: 'bold',
  fontSize: 16,
},
  actionButton: {
    backgroundColor: 'rgba(218,165,32,0.8)',
    padding: 15,
    borderRadius: 20,
    minWidth: 150,
    alignItems: 'center',
  },
  continueButton: {
    backgroundColor: 'rgba(0,200,0,0.8)',
  },
  actionButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  nextRoundButton: {
    backgroundColor: 'rgba(218,165,32,0.8)',
    padding: 15,
    borderRadius: 20,
    marginTop: 20,
  },
  nextRoundButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
  },
  turnIndicator: {
  position: 'absolute',
  top: -10,
  backgroundColor: 'gold',
  paddingHorizontal: 8,
  paddingVertical: 2,
  borderRadius: 10,
},
turnIndicatorText: {
  color: 'black',
  fontWeight: 'bold',
  fontSize: 12,
},
// Add these to your styles
errorContainer: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0,0,0,0.8)',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 1000,
},
errorText: {
  color: 'white',
  fontSize: 18,
  marginBottom: 20,
},
retryText: {
  color: 'blue',
  fontSize: 16,
},
loadingContainer: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0,0,0,0.8)',
  justifyContent: 'center',
  alignItems: 'center',
  zIndex: 1000,
},
loadingText: {
  color: 'white',
  fontSize: 18,
},
errorBanner: {
  position: 'absolute',
  top: 80,
  left: 20,
  right: 20,
  backgroundColor: 'red',
  padding: 10,
  borderRadius: 5,
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  zIndex: 1000,
},
menuContainer: {
  backgroundColor: 'rgba(40, 40, 80, 0.9)',
  borderRadius: 20,
  padding: 20,
  width: '50%',
  maxWidth: 400,
  alignItems: 'center',
  borderWidth: 2,
  borderColor: '#FFD700',
  position: 'relative',
},
menuItemText: {
  color: 'white',
  fontSize: 18,
  marginLeft: 15,
},
menuOption: {
  alignItems: 'center',
  padding: 20,
  minWidth: 100,
},
 menuIconContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
menuOptionText: {
  color: '#FFD700',
  fontSize: 16,
  fontWeight: 'bold',
  textAlign: 'center',
},
menuOptionsRow: {
  flexDirection: 'row',
  justifyContent: 'space-around',
  width: '100%',
  marginTop: 20,
},
winnerModalContent: {
  backgroundColor: '#1e1e2f',
  padding: 20,
  borderRadius: 16,
  alignItems: 'center',
  justifyContent: 'center',
  shadowColor: '#000',
  shadowOpacity: 0.3,
  shadowRadius: 8,
  elevation: 6,
},

winnerTitle: {
  fontSize: 24,
  fontWeight: 'bold',
  color: '#FFD700', // gold
  marginBottom: 12,
},

winnerName: {
  fontSize: 20,
  fontWeight: '600',
  color: '#ffffff',
  marginBottom: 6,
},

winnerAmount: {
  fontSize: 18,
  fontWeight: '500',
  color: '#00FF7F', // greenish for chips
  marginBottom: 6,
},

winnerHand: {
  fontSize: 16,
  fontStyle: 'italic',
  color: '#cccccc',
},
checkButton: {
    backgroundColor: "#2196F3",
    padding: 10,
    borderRadius: 8,
    marginHorizontal: 5,
  },
  handDescription: {
  fontSize: 14,
  color: '#aaaaaa',
  marginTop: 4,
  textAlign: 'center',
},
 currentPlayerHighlight: {
    borderWidth: 2,
    borderColor: 'gold',
    backgroundColor: 'rgba(255, 215, 0, 0.1)',
  },
  chatContainer: {
  position: 'absolute',
  bottom: 80,
  right: 20,
  width: 300,
  height: 300,
  backgroundColor: 'rgba(0, 0, 0, 0.9)',
  borderRadius: 10,
  borderWidth: 1,
  borderColor: '#FFD700',
  zIndex: 1000,
},
chatHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  padding: 10,
  borderBottomWidth: 1,
  borderBottomColor: '#FFD700',
},
chatTitle: {
  color: '#FFD700',
  fontSize: 16,
  fontWeight: 'bold',
},
chatMessages: {
  flex: 1,
  padding: 10,
},
chatMessage: {
  marginBottom: 8,
  padding: 8,
  borderRadius: 8,
},
myMessage: {
  backgroundColor: 'rgba(255, 215, 0, 0.2)',
  alignSelf: 'flex-end',
},
otherMessage: {
  backgroundColor: 'rgba(255, 255, 255, 0.1)',
  alignSelf: 'flex-start',
},
messageSender: {
  color: '#FFD700',
  fontSize: 12,
  fontWeight: 'bold',
},
messageText: {
  color: 'white',
  fontSize: 14,
},
messageTime: {
  color: '#ccc',
  fontSize: 10,
  alignSelf: 'flex-end',
},

chatBadge: {
  position: 'absolute',
  top: -5,
  right: -5,
  backgroundColor: 'red',
  borderRadius: 10,
  minWidth: 20,
  height: 20,
  justifyContent: 'center',
  alignItems: 'center',
},
chatBadgeText: {
  color: 'white',
  fontSize: 12,
  fontWeight: 'bold',
},
countdownContainer: {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: [{ translateX: -100 }, { translateY: -25 }],
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  padding: 20,
  borderRadius: 10,
  zIndex: 1000,
},
countdownText: {
  color: '#FFD700',
  fontSize: 24,
  fontWeight: 'bold',
  textAlign: 'center',
},
});